version: '3'
services:
  front:
    image: nginx:latest
    volumes:
        - ./front-nginx.conf:/etc/nginx/nginx.conf
        - ./cert:/etc/nginx/cert
    ports:
        - "8000:8000"
        - "8001:8001"
        - "443:443"      
    links:
        - front-project1
        - front-project2
        - front-project3
        - front-project4

  back:
    image: nginx:latest
    volumes:
        - ./back-nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8080:8080"
    links:
        - back-project1
        - back-project2
        - back-project3

  front-project1:
    build: ./Dockerfile-front
    command: node /usr/src/maoyan-front/bin/www
    expose:
        - "3000"
    links:
        - maoyan-redis

  front-project2:
    build: ./Dockerfile-front
    command: node /usr/src/maoyan-front/bin/www
    expose:
        - "3000"
    links:
        - maoyan-redis

  front-project3:
    build: ./Dockerfile-front
    command: node /usr/src/maoyan-front/bin/www
    expose:
        - "3000"
    links:
        - maoyan-redis

  front-project4:
    build: ./Dockerfile-front-weixin
    command: node /usr/src/maoyan-front-weixin/bin/www
    expose:
        - "3000"
    links:
        - maoyan-redis

  back-project1:
    build: ./Dockerfile-back
    expose:
        - "8080"
    links:
        - maoyan-db

  back-project2:
    build: ./Dockerfile-back
    expose:
        - "8080"
    links:
        - maoyan-db

  back-project3:
    build: ./Dockerfile-back
    expose:
        - "8080"
    links:
        - maoyan-db

  maoyan-db:
    image: mysql:latest
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=maoyan
        
  maoyan-redis:
    image: redis:latest
    ports:
        - "6379:6379"
